# Discussion 9: July 12th, 2024

## Timing a compuation using NumPy vs base Python

In [4]:
import numpy as np

In [5]:
rng = np.random.default_rng()

In [6]:
arr = rng.integers(1, 10, size = 10**6)

Look @ first 5 elements of arr, divide 1.5 by each element

In [7]:
arr[:5]

array([7, 8, 4, 1, 2])

In [8]:
1.5/arr[:5]

array([0.21428571, 0.1875    , 0.375     , 1.5       , 0.75      ])

Can we do the same thing with a list?

In [9]:
mylist = list(arr)

In [10]:
mylist[:5]

[7, 8, 4, 1, 2]

In [11]:
#method 1 -- use a for loop
newlist = []
for x in mylist[:5]:
    newlist.append(1.5/x)
newlist

[0.21428571428571427, 0.1875, 0.375, 1.5, 0.75]

In [12]:
#method 2 -- list comprehension
[1.5/x for x in mylist[:5]]

[0.21428571428571427, 0.1875, 0.375, 1.5, 0.75]

## Timing computations

In [13]:
%%timeit
1.5/arr[:5]

1.54 µs ± 66 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
%%timeit
newlist = []
for x in mylist[:5]:
    newlist.append(1.5/x)

8.37 µs ± 429 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
%%timeit
[1.5/x for x in mylist[:5]]

8.41 µs ± 431 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Counting using NumPy

__Goal:__ Use NumPy to estimate probilities

In [16]:
#importy numpy as np
#rng = np.random.default_rng()

In [17]:
n = 10**7

- (a) Make a NumPy array of random integers between -50 and 50 inclusive. Make a list of the same numbers.

In [18]:
arr = rng.integers(-50, 51, size=n)

In [19]:
mylist = list(arr)

- (b) How many of the integers are less than 10?

In [20]:
count = 0
for x in mylist:
    if x < 10:
        count += 1
count

5942811

In [21]:
len([x for x in mylist if x < 10])

5942811

In [22]:
arr < 10

array([ True,  True,  True, ..., False, False, False])

In [23]:
np.count_nonzero(arr < 10)

5942811

- (c) At what indices do these integers less than 10 occur?

In [24]:
np.nonzero(arr < 10)

(array([      0,       1,       2, ..., 9999992, 9999993, 9999994]),)

- (d) Make a new array containing only these integers.

In [27]:
newlist = []
for x in mylist:
    if x < 10:
        newlist.append(x)

In [30]:
#[x for x in mylist if x < 10]

In [31]:
arr[arr < 10]

array([-13, -49, -18, ..., -46, -15, -17])

- (e) If you pick a random integer from the original array, what is the probability it is less than 10? How long does each method take?

In [32]:
%%timeit
count = 0
for x in mylist:
    if x < 10:
        count += 1
count/n

784 ms ± 35.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [33]:
%%timeit
len([x for x in mylist if x < 10])/n

643 ms ± 4.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [34]:
%%timeit
np.count_nonzero(arr < 10)/n

5.32 ms ± 41.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
