# Lecture 10: July 15th, 2024

## Random Numbers

__Note:__ I’m first going to show you the old way of generating random numbers in NumPy. If you’re reading older code, this is likely the way you’ll see random numbers generated. All new code should be written using the new method that I show you.

__Older Method:__ Don't use this!

In [1]:
import numpy as np

In [6]:
np.random.randint(0,39,size=10)

array([ 1, 16,  7, 27, 14, 14, 12, 16, 35, 11])

In [7]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

__New Method:__ This is an example of object oriented programming (OOP)

In [8]:
rng = np.random.default_rng()

In [9]:
type(rng)

numpy.random._generator.Generator

* Make a length 10 NumPy array of random integers between 0 (inclusive) and 39 (exclusive).

In [12]:
arr = rng.integers(0,39,size=10)

In [13]:
arr

array([34, 14, 35,  4, 12, 33,  9,  4,  7, 13])

* Choose five of those numbers (with replacement) and put them into a NumPy array.

In [17]:
rng.choice(arr,size=5)

array([ 7,  9, 33,  4, 34])

* Create a $3 \times 5$ NumPy array of random real numbers between -1 and 4.

You might expect this to work, but it won't :(

In [18]:
rng.random(-1,4,size=(3,5))

TypeError: random() got multiple values for keyword argument 'size'

In [19]:
help(rng.random)

Help on built-in function random:

random(...) method of numpy.random._generator.Generator instance
    random(size=None, dtype=np.float64, out=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random` by `(b-a)` and add `a`::
    
      (b - a) * random() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    dtype : dtype, optional
        Desired dtype of the result, only `float64` and `float32` are supported.
        Byteorder must be native. The default value is np.float64.
    out : ndarray, optional
        Alternative output array in which to place the result. If size is not None,
        it

In [20]:
#3x5 array of random reals between 0 and 1
rng.random((3,5))

array([[0.64507008, 0.67379237, 0.51311786, 0.25533235, 0.67632905],
       [0.37574593, 0.07156593, 0.64920836, 0.16700755, 0.61146585],
       [0.76778512, 0.66203774, 0.11459042, 0.80753282, 0.36854056]])

In [26]:
#Mult. by 5 to stretch to correct length
#subtract 1 to shift to correct interval.
5*rng.random((3,5))-1

array([[ 0.99418412,  3.12855921,  0.51653622,  3.26446123,  3.8135536 ],
       [ 0.02610254,  2.74374805,  0.91648143,  3.69761248,  3.66140139],
       [ 0.37319287,  3.21238436, -0.2789946 ,  2.03303439,  1.22084951]])

Running the above cell a few times, we see that we can get pretty close to both -1 and 4.

* Create a length 10 NumPy array of random numbers that follow a normal distribution with mean 2 and standard deviation 0.1.

This isn't super important for our class, I just wanted to show it as an example.

In [27]:
help(rng.normal)

Help on built-in function normal:

normal(...) method of numpy.random._generator.Generator instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int o

In [28]:
rng.normal(2,0.1,size=10)

array([2.02447833, 1.98771984, 2.16976678, 1.88179728, 2.00441802,
       2.04740595, 1.87634428, 1.89205649, 1.99836371, 2.05844611])

Notice: the values are clustered around 2, and if they deviate from the average, it's likely within 0.1.

## Changing Rows and Columns 

__Goal:__ Modify rows and columns of NumPy arrays.

In [1]:
import numpy as np

In [29]:
arr = np.zeros((4,4),dtype=int)
for i in range(4):
    arr[i] = i
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

Recall:

In [31]:
arr[3,:]

array([3, 3, 3, 3])

In [35]:
arr[3]

array([3, 3, 3, 3])

In [32]:
v = arr[:,2]

In [33]:
v

array([0, 1, 2, 3])

In [34]:
v.shape

(4,)

`v` is a 1-dimensional NumPy array of length 4.

In [36]:
arr[3]

array([3, 3, 3, 3])

In [37]:
arr[3] = [2,10]

ValueError: could not broadcast input array from shape (2,) into shape (4,)

The error is basically saying "I don't know how to stretch a length 2 array into a length 4 array".

In [39]:
arr[3] = [2,10,2,10]
arr

array([[ 0,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 2,  2,  2,  2],
       [ 2, 10,  2, 10]])

In [41]:
arr[0] = 5
arr

array([[ 5,  5,  5,  5],
       [ 1,  1,  1,  1],
       [ 2,  2,  2,  2],
       [ 2, 10,  2, 10]])

These are examples of something called broadcasting, which we'll see next in lecture.

In [43]:
#Make a prediction
arr[:] = [1,3,4,7]
arr

array([[1, 3, 4, 7],
       [1, 3, 4, 7],
       [1, 3, 4, 7],
       [1, 3, 4, 7]])

In [44]:
arr.shape

(4, 4)

In [45]:
w = np.array([1,3,4,7])

In [46]:
w.shape

(4,)

Let's try to make this $5 \times 5$ array using broadcasting.

In [47]:
arr = np.zeros((5,5),dtype=int)
for i in range(5):
    arr[i] = i
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [49]:
arr = np.zeros((5,5),dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [50]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [52]:
arr[:] = np.arange(5)
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [54]:
#transpose
arr = arr.T
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [55]:
np.arange(5).shape

(5,)

In [57]:
arr[:] = np.arange(5).reshape((5,1))
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [58]:
z = np.arange(5).reshape((5,1))

In [59]:
z.shape

(5, 1)

In [61]:
arr[:] = np.arange(5).reshape((-1,1))
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

The $-1$ in the above means "give me any dimension that forces this to work".

In [63]:
arr.reshape(-1).shape

(25,)

Here, the -1 means fit everything into a 1-dimensional NumPy array. Since `arr` has 25 elements, we get a length 25 array.

## Broadcasting

![](../images/12.jpg)
![](../images/13.jpg)
![](../images/14.jpg)
![](../images/15.jpg)
![](../images/16.jpg)
![](../images/17.jpg)
![](../images/18.jpg)
![](../images/19.jpg)
![](../images/20.jpg)
![](../images/21.jpg)
![](../images/22.jpg)

## Logic in Python vs. Logic in NumPy

### General Rules

* In base Python: `and`, `or`, `not`
* In NumPy (and pandas): `&`, `|`, `~`

In [2]:
import numpy as np

In [64]:
rng = np.random.default_rng()
n = 20
arr = rng.integers(-50,51, size=n)
mylist = list(arr)

In [65]:
mylist

[28,
 37,
 40,
 -16,
 37,
 -47,
 -19,
 -43,
 16,
 32,
 42,
 43,
 0,
 8,
 -15,
 -38,
 -46,
 -24,
 -49,
 12]

__Motivating Question:__ Find all entries in `arr` and `mylist` that are strictly between -10 and 10.

Let's start with the list. We'll do it with something called "list comprehension".

In [66]:
[x for x in mylist if (x > -10) and (x < 10)]

[0, 8]

As an example, notice that if I use `&` there is no erorr. However, I want to avoid doing this. It won't always work the way you expect.

In [67]:
[x for x in mylist if (x > -10) & (x < 10)]

[0, 8]

Practice with negation, and so that we can practice using `or` and `not`.

In [68]:
[x for x in mylist if not((x <= -10) or (x >= 10))]

[0, 8]

In [69]:
[x for x in mylist if not(x <= -10) and not(x >= 10)]

[0, 8]

In [70]:
arr

array([ 28,  37,  40, -16,  37, -47, -19, -43,  16,  32,  42,  43,   0,
         8, -15, -38, -46, -24, -49,  12])

Now, let's practice with NumPy arrays.

In [71]:
(arr > -10) & (arr < 10)

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False])

This is an example of a boolean array. For each entry of `arr` it returns `True` if the corresponding entry is between -10 and 10, and `False` otherwise.

In [74]:
arr[(arr > -10) & (arr < 10)]

array([0, 8])

This is an example of boolean indexing.

Now let's get some practice with negation.

In [75]:
arr[~((arr <= -10) | (arr >= 10))]

array([0, 8])

In [76]:
arr[~(arr <= -10) & ~(arr >= 10)]

array([0, 8])

In [72]:
#Notice we get an error
(arr > -10) and (arr < 10)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## The `axis` keyword argument

__Motivating Question:__ If you roll 4 distinct 6-sided dice, what is the probability that the largest value is 5?

The code below models rolling 4 dice.

In [79]:
rng.integers(1,7,size=4)

array([3, 1, 5, 4])

Let's start by coding this is the way we're most familiar with.

In [85]:
exp = 10
s = 0
for i in range(exp):
    if np.max(rng.integers(1,7,size=4)) == 5:
        s += 1 #shorthand for s = s+1
s/exp

0.1

for-loops are extremely slow! We'll see that in just a minute. Remember the Jupyter magic `%%timeit` – the `it` means iteration, and it runs the code a number of times and computes average time. This will be too slow for this example, so we'll use `%%time`.

In [87]:
%%time
exp = 10**6
s = 0
for i in range(exp):
    if np.max(rng.integers(1,7,size=4)) == 5:
        s += 1 #shorthand for s = s+1
s/exp

CPU times: user 23.6 s, sys: 371 ms, total: 23.9 s
Wall time: 24.2 s


0.284255

In [88]:
exp = 10
rng.integers(1,7,size=(exp,4))

array([[1, 3, 3, 6],
       [6, 6, 5, 5],
       [2, 6, 4, 5],
       [6, 4, 4, 3],
       [3, 6, 2, 2],
       [5, 6, 6, 1],
       [3, 3, 2, 2],
       [5, 6, 5, 4],
       [6, 3, 3, 2],
       [3, 6, 2, 1]])

Here, each row of the array represents an experiment.

In [89]:
arr = rng.integers(1,7,size=(exp,4))
print(arr)

[[6 2 5 2]
 [3 1 2 2]
 [1 5 1 4]
 [6 2 4 5]
 [3 4 2 5]
 [2 3 1 4]
 [3 6 5 5]
 [2 3 5 5]
 [4 3 3 5]
 [3 2 6 2]]


The first method I'm going to show you is extremely flexible in that it will work for really any function I want – the drawback is that it will also be quite slow.

In [90]:
help(np.apply_along_axis)

Help on function apply_along_axis in module numpy:

apply_along_axis(func1d, axis, arr, *args, **kwargs)
    Apply a function to 1-D slices along the given axis.
    
    Execute `func1d(a, *args, **kwargs)` where `func1d` operates on 1-D arrays
    and `a` is a 1-D slice of `arr` along `axis`.
    
    This is equivalent to (but faster than) the following use of `ndindex` and
    `s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                f = func1d(arr[ii + s_[:,] + kk])
                Nj = f.shape
                for jj in ndindex(Nj):
                    out[ii + jj + kk] = f[jj]
    
    Equivalently, eliminating the inner loop, this can be expressed as::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                out[ii + s_[...,] + kk] = func1d(arr[ii 

`axis` simply means the direction I want to do the computation along.

In [91]:
print(arr)

[[6 2 5 2]
 [3 1 2 2]
 [1 5 1 4]
 [6 2 4 5]
 [3 4 2 5]
 [2 3 1 4]
 [3 6 5 5]
 [2 3 5 5]
 [4 3 3 5]
 [3 2 6 2]]


In [92]:
np.apply_along_axis(np.max, axis=1, arr=arr)

array([6, 3, 5, 6, 5, 4, 6, 5, 5, 6])

Try to predict what will happen when I run the following:

In [93]:
np.apply_along_axis(np.max, axis=0, arr=arr)

array([6, 6, 6, 5])

In [98]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()

0.3

Now, let's time this with $10^6$ experiments. You might be surprised to see that it's still pretty slow.

In [99]:
%%time
exp = 10**6
arr = rng.integers(1,7,size=(exp,4))
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()

CPU times: user 13.6 s, sys: 322 ms, total: 13.9 s
Wall time: 14.9 s


0.285004

The reason this is slower than we expect is because `np.apply_along_axis` is not optimized for this kind of computation. It has to be flexible enough to work with almost any function we give it. 

In [104]:
exp = 10
arr = rng.integers(1,7,size=(exp,4))
(arr.max(axis=1) == 5).mean()

0.1

In [106]:
#1-Dimensional
(arr.max(axis=1) == 5)

array([False, False, False, False, False, False, False, False, False,
        True])

In [108]:
#axis = 0 is the default
(arr.max(axis=1) == 5).mean(axis=0)

0.1

The following throws and error, since the array only has one dimension. We only talk about `axis=1` when there are at least two dimensions.

In [109]:
(arr.max(axis=1) == 5).mean(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [101]:
help(arr.max)

Help on built-in function max:

max(...) method of numpy.ndarray instance
    a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the maximum along a given axis.
    
    Refer to `numpy.amax` for full documentation.
    
    See Also
    --------
    numpy.amax : equivalent function



In [110]:
%%time
exp = 10**6
arr = rng.integers(1,7,size=(exp,4))
(arr.max(axis=1) == 5).mean()

CPU times: user 67 ms, sys: 3.22 ms, total: 70.2 ms
Wall time: 68.8 ms


0.284987

Wow! So fast!

## More on the `axis` keyword argument

![](../images/23.jpg)
![](../images/24.jpg)
![](../images/25.jpg)