# Lecture 11: July 17th, 2024 

In [17]:
import numpy as np

## An exact probability 

__Goal:__ Compute the exact probability of the question from last time. 

<blockquote>If you roll 4 distinct 6-sided dice, what is the probability that the largest value is 5?</blockquote>

I claim that we can compute an exact value. Notice that there are only 1296 total outcomes. We can definitely iterate through all of them.

In [1]:
6**4

1296

The idea now is that we'll list out all of the possible outcomes, and count how many of them have 5 as the largest number. The first method is what you might think to do first, and then I'll show you a more elegant way.

In [2]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash

In [3]:
all_dice = []

for i in range(1,7):
    for j in range(1,7):
        for k in range(1,7):
            for l in range(1,7):
                all_dice.append((i,j,k,l))

In [4]:
len(all_dice)

1296

Try to predict what this will look like before we run the code. It's good practice for iterating through nested for-loops.

In [5]:
all_dice[:10]

[(1, 1, 1, 1),
 (1, 1, 1, 2),
 (1, 1, 1, 3),
 (1, 1, 1, 4),
 (1, 1, 1, 5),
 (1, 1, 1, 6),
 (1, 1, 2, 1),
 (1, 1, 2, 2),
 (1, 1, 2, 3),
 (1, 1, 2, 4)]

Some things that are not-so-great about this for-loop method:

* Time efficiency 
* There's a lot of repetition. There's the concept of DRY (Don't Repeat Yourself) code. Notice that we've repeated ourselves a lot! 
    * Any time you see yourself writing the same line of code over and over again, there's usually a better way to do it.

In [6]:
from itertools import product

In [7]:
help(product)

Help on class product in module itertools:

class product(builtins.object)
 |  product(*iterables, repeat=1) --> product object
 |  
 |  Cartesian product of input iterables.  Equivalent to nested for-loops.
 |  
 |  For example, product(A, B) returns the same as:  ((x,y) for x in A for y in B).
 |  The leftmost iterators are in the outermost for-loop, so the output tuples
 |  cycle in a manner similar to an odometer (with the rightmost element changing
 |  on every iteration).
 |  
 |  To compute the product of an iterable with itself, specify the number
 |  of repetitions with the optional repeat keyword argument. For example,
 |  product(A, repeat=4) means the same as product(A, A, A, A).
 |  
 |  product('ab', range(3)) --> ('a',0) ('a',1) ('a',2) ('b',0) ('b',1) ('b',2)
 |  product((0,1), (0,1), (0,1)) --> (0,0,0) (0,0,1) (0,1,0) (0,1,1) (1,0,0) ...
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /

In [9]:
#let's start with repeat=2 just to see what's going on
list(product(range(1,7),repeat=2))

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)]

In [10]:
temp_list = list(product(range(1,7),repeat=4))

Let's see a few more examples with `product` before we go in and compute the probability.

In [11]:
list(product(["a","b","c"],[5,6])) #cartesian product

[('a', 5), ('a', 6), ('b', 5), ('b', 6), ('c', 5), ('c', 6)]

Notice the use of repeat in the following example.

In [14]:
list(product(["a","b","c"],["a","b","c"],["a","b","c"]))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [13]:
list(product(["a","b","c"],repeat=3))

[('a', 'a', 'a'),
 ('a', 'a', 'b'),
 ('a', 'a', 'c'),
 ('a', 'b', 'a'),
 ('a', 'b', 'b'),
 ('a', 'b', 'c'),
 ('a', 'c', 'a'),
 ('a', 'c', 'b'),
 ('a', 'c', 'c'),
 ('b', 'a', 'a'),
 ('b', 'a', 'b'),
 ('b', 'a', 'c'),
 ('b', 'b', 'a'),
 ('b', 'b', 'b'),
 ('b', 'b', 'c'),
 ('b', 'c', 'a'),
 ('b', 'c', 'b'),
 ('b', 'c', 'c'),
 ('c', 'a', 'a'),
 ('c', 'a', 'b'),
 ('c', 'a', 'c'),
 ('c', 'b', 'a'),
 ('c', 'b', 'b'),
 ('c', 'b', 'c'),
 ('c', 'c', 'a'),
 ('c', 'c', 'b'),
 ('c', 'c', 'c')]

In [12]:
for x in ["a","b","c"]:
    print(x)

a
b
c


In [16]:
len(temp_list)

1296

In [18]:
arr = np.array(temp_list)

In [20]:
arr[:10]

array([[1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 3],
       [1, 1, 1, 4],
       [1, 1, 1, 5],
       [1, 1, 1, 6],
       [1, 1, 2, 1],
       [1, 1, 2, 2],
       [1, 1, 2, 3],
       [1, 1, 2, 4]])

In [19]:
arr.shape

(1296, 4)

In [24]:
#here is our exact probability
(arr.max(axis = 1) == 5).mean()

0.2847222222222222

In [25]:
#Mathematically
(5/6)**4 - (4/6)**4

0.2847222222222223

## `any` and `all` 

In [26]:
rng = np.random.default_rng()

* Make a 100 row, 4 column NumPy array of random real numbers between 0 and 1.

In [31]:
rng.random()

0.5785174345640893

In [33]:
arr = rng.random(size=(100,4))

In [34]:
arr[:5]

array([[0.40624337, 0.5378342 , 0.82133773, 0.8894171 ],
       [0.74711459, 0.11780409, 0.1364746 , 0.55430406],
       [0.98098738, 0.12213209, 0.99136173, 0.42695145],
       [0.33435934, 0.11342574, 0.81749248, 0.00476634],
       [0.92969382, 0.95581602, 0.86704815, 0.53561191]])

* Find the subarray containing all rows in which at least one number is greater than 0.9

Let's practice with the first 5 rows, and then we'll do the whole array.

In [36]:
(arr[:5] > 0.9).any(axis=1)

array([False, False,  True, False,  True])

In [37]:
(arr[:5] > 0.9).any(axis=1).sum()

2

Here's an example of boolean indexing, where we keep only the rows where at least one element is larger than 0.9.

In [38]:
arr[:5][(arr[:5] > 0.9).any(axis=1)]

array([[0.98098738, 0.12213209, 0.99136173, 0.42695145],
       [0.92969382, 0.95581602, 0.86704815, 0.53561191]])

Now for the whole array, and not just the first 5 rows.

In [39]:
arr[(arr > 0.9).any(axis=1)]

array([[0.98098738, 0.12213209, 0.99136173, 0.42695145],
       [0.92969382, 0.95581602, 0.86704815, 0.53561191],
       [0.26299191, 0.91725939, 0.7396239 , 0.35315734],
       [0.76424767, 0.07296775, 0.98504967, 0.71837278],
       [0.92948207, 0.85994845, 0.67447024, 0.2477325 ],
       [0.30571581, 0.46302444, 0.94687297, 0.79040623],
       [0.97422121, 0.8194787 , 0.05402564, 0.38577634],
       [0.94444593, 0.79932293, 0.11396907, 0.32188097],
       [0.90704845, 0.22689578, 0.77330896, 0.54458391],
       [0.94224102, 0.9382032 , 0.46842465, 0.84812382],
       [0.65333607, 0.95023806, 0.27546515, 0.84692087],
       [0.53447862, 0.41772819, 0.5545759 , 0.97497601],
       [0.25089317, 0.97460391, 0.39827117, 0.21373961],
       [0.18454744, 0.28763993, 0.9997678 , 0.60633733],
       [0.73136688, 0.90193453, 0.08807143, 0.39348309],
       [0.90390872, 0.3967107 , 0.46807354, 0.35973876],
       [0.17114071, 0.94207451, 0.35474207, 0.28944731],
       [0.11979512, 0.83620929,

* Find the subarray containing all rows in which no numbers are between 0.4 and 0.6.

In [40]:
arr[:5]

array([[0.40624337, 0.5378342 , 0.82133773, 0.8894171 ],
       [0.74711459, 0.11780409, 0.1364746 , 0.55430406],
       [0.98098738, 0.12213209, 0.99136173, 0.42695145],
       [0.33435934, 0.11342574, 0.81749248, 0.00476634],
       [0.92969382, 0.95581602, 0.86704815, 0.53561191]])

In [46]:
((arr[:5] < 0.4)|(arr[:5] > 0.6))

array([[False, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [42]:
((arr[:5] < 0.4)|(arr[:5] > 0.6)).all(axis=1)

array([False, False, False,  True, False])

In [44]:
((arr < 0.4)|(arr > 0.6)).all(axis=1).shape

(100,)

To get the full subarray

In [45]:
arr[((arr < 0.4)|(arr > 0.6)).all(axis=1)]

array([[0.33435934, 0.11342574, 0.81749248, 0.00476634],
       [0.26299191, 0.91725939, 0.7396239 , 0.35315734],
       [0.76424767, 0.07296775, 0.98504967, 0.71837278],
       [0.92948207, 0.85994845, 0.67447024, 0.2477325 ],
       [0.14636106, 0.81629512, 0.31269615, 0.28734118],
       [0.97422121, 0.8194787 , 0.05402564, 0.38577634],
       [0.37546177, 0.75619981, 0.35022317, 0.30633374],
       [0.70263436, 0.82449652, 0.78041626, 0.08655296],
       [0.94444593, 0.79932293, 0.11396907, 0.32188097],
       [0.04706312, 0.12133183, 0.78534269, 0.62352465],
       [0.65333607, 0.95023806, 0.27546515, 0.84692087],
       [0.25317025, 0.16095503, 0.73573737, 0.28610559],
       [0.25089317, 0.97460391, 0.39827117, 0.21373961],
       [0.84831992, 0.03557131, 0.16619586, 0.86691926],
       [0.08338736, 0.07626593, 0.0066986 , 0.74342543],
       [0.77255364, 0.26095486, 0.06480588, 0.29481606],
       [0.01446364, 0.86841444, 0.17721023, 0.09872224],
       [0.10063076, 0.72317332,

## Binary to Decimal: Version 1 

$$
\begin{pmatrix}
1 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
1 & 1 & 1 & 1
\end{pmatrix} \mapsto
\begin{pmatrix}
10 \\
4 \\
15
\end{pmatrix}
$$

__Goal:__ Write a function `to_bin` which takes as input an $m \times n$ NumPy array of 0s and 1s, and as output returns the corresponding base 10 integers (we think of each row as representing the binary digits of an integer).

Let's talk a little bit about converting between binary and decimal. Jessica will cover more, but here are the basics.

Someone give me a number between 100 and 1000: 170. 
* In decimal, we use the digits 0-9 and multiply with powers of 10.

$170 = 100 + 70 + 0 = 1 \times 10^2 + 7 \times 10^1 + 0 \times 10^0$

$543 = 5 \times 10^2 + 4 \times 10^1 + 3 \times 10^0$

* In binary, we use digits 0-1 and multiply with powers of 2.

$1010 = 1 \times 2^3 + 0 \times 2^2 + 1 \times 2^1 + 0 \times 2^0 = 8 + 2 = 10$ 

Let's try to get all of our ideas together, and then write the function.

In [47]:
arr = rng.integers(2,size=(10,4))

In [48]:
arr

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]])

In [50]:
#tuple unpacking
m,n = arr.shape

In [54]:
arr.shape

(10, 4)

In [52]:
m

10

In [53]:
n

4

These are the powers of 2 that I will be taking.

In [55]:
np.arange(n-1,-1,-1)

array([3, 2, 1, 0])

In [56]:
2**np.arange(n-1,-1,-1)

array([8, 4, 2, 1])

In [57]:
arr

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]])

In [58]:
arr*2**np.arange(n-1,-1,-1)

array([[0, 0, 2, 1],
       [0, 4, 2, 0],
       [8, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [8, 4, 0, 1],
       [0, 0, 0, 1],
       [8, 4, 0, 0],
       [0, 4, 2, 1]])

In [59]:
(arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

array([ 3,  6,  9,  1,  0,  0, 13,  1, 12,  7])

In [60]:
def to_bin(arr):
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [61]:
to_bin(arr)

array([ 3,  6,  9,  1,  0,  0, 13,  1, 12,  7])

In [62]:
to_bin(np.array([[1,1],[1,0]]))

array([3, 2])

## Binary to Decimal: Version 2 

We want to write a function that does the same thing as `to_bin` above, but now let's write it using a different idea.

In [63]:
arr

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]])

Here's the idea for the new function.

In [64]:
int("1001")

1001

In [65]:
int("1001",2)

9

In [66]:
int("1001",10)

1001

Let's test this idea outside of a function, and then put it all together once we have it working.

In [67]:
z = arr[0]

In [69]:
z

array([0, 0, 1, 1])

In [70]:
[x for x in z]

[0, 0, 1, 1]

In [71]:
[str(x) for x in z]

['0', '0', '1', '1']

In [72]:
''.join([str(x) for x in z])

'0011'

In [90]:
def helper(z):
    temp = ''.join([str(x) for x in z])
    return int(temp,2)

In [91]:
helper(z)

3

In [92]:
helper(arr[1])

6

In [94]:
def to_bin2(A):
    return np.apply_along_axis(helper, axis=1,arr=A)

In [95]:
to_bin2(arr)

array([ 3,  6,  9,  1,  0,  0, 13,  1, 12,  7])

## Raising Errors 

__Goal:__ Edit the `to_bin` function so that it raises an error if the input is not a NumPy array and also if an entry is not 0 or 1.

In [96]:
def to_bin(arr):
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [97]:
arr

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]])

In [98]:
type(arr)

numpy.ndarray

You might be tempted to check `type(arr) == np.ndarray`, but this is something you'll almost never see in practice.

Here's how we check instead:

In [99]:
isinstance(arr,np.ndarray)

True

In [100]:
isinstance(list(arr),np.ndarray)

False

In [101]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

In [102]:
to_bin("Hello")

TypeError: Input should be a NumPy array.

In [103]:
to_bin(arr)

array([ 3,  6,  9,  1,  0,  0, 13,  1, 12,  7])

In [104]:
to_bin([1,2,3])

TypeError: Input should be a NumPy array.

Now let's check if each entry is 0 or 1.

In [105]:
arr == 0

array([[ True,  True, False, False],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True,  True, False],
       [False, False,  True,  True],
       [ True, False, False, False]])

In [106]:
arr == 1

array([[False, False,  True,  True],
       [False,  True,  True, False],
       [ True, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True, False,  True],
       [False, False, False,  True],
       [ True,  True, False, False],
       [False,  True,  True,  True]])

In [109]:
#Check if every entry is 0 or 1
((arr == 0) | (arr == 1)).all()

True

In [110]:
def to_bin(arr):
    if not isinstance(arr,np.ndarray):
        raise TypeError("Input should be a NumPy array.")
    if not ((arr == 0) | (arr == 1)).all():
        raise ValueError("All entries should be 0 or 1.")
    _,n = arr.shape
    return (arr*2**np.arange(n-1,-1,-1)).sum(axis=1)

Now, let's try to test our function. I'm going to make a subtle mistake below. I want to make an array that's not all 0s/1s.

In [112]:
arr
arr2 = arr

In [113]:
arr2[5,2] = 6

In [114]:
arr2

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 6, 0],
       [1, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]])

In [115]:
to_bin(arr2)

ValueError: All entries should be 0 or 1.

This is good, the function is behaving exactly as we would expect. However, notice that the following also throws an error.

In [116]:
to_bin(arr)

ValueError: All entries should be 0 or 1.

The basic idea here is that `arr` and `arr2` point to the same object in memory. When one gets changed, so does the other. (Don't worry so much about why this happens, unless you're interested :))

__Upshot:__ If I want to change values, I need to make a copy.

In [117]:
arr3 = arr2.copy()

In [118]:
arr3[6,1::2] = 99

In [119]:
arr3

array([[ 0,  0,  1,  1],
       [ 0,  1,  1,  0],
       [ 1,  0,  0,  1],
       [ 0,  0,  0,  1],
       [ 0,  0,  0,  0],
       [ 0,  0,  6,  0],
       [ 1, 99,  0, 99],
       [ 0,  0,  0,  1],
       [ 1,  1,  0,  0],
       [ 0,  1,  1,  1]])

In [120]:
arr2

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 6, 0],
       [1, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]])

***

The next few portions of lecture will be about something called "Pythonic Code". This more or less refers to things that are unique-ish to Python.

## List Comprehension – Pythonic Code 1 

__Words of Advice:__ If you're ever confused about how to write something with list comprehension, think about how you'd write it with a for-loop, and then convert it.

__Benefit:__ Code written with list comprehension is usually more readable than for-loops, but don't expect it to run any faster.

* Length 8 list of all 7s.

Let's think about how we'd do this with for-loops.

In [122]:
mylist = []
for i in range(8):
    mylist.append(7)
mylist

[7, 7, 7, 7, 7, 7, 7, 7]

In [123]:
[7 for _ in range(8)]

[7, 7, 7, 7, 7, 7, 7, 7]

* Let `mylist = [-1,4,2,3,-10,2,4]`. Square each element in `mylist`.

In [124]:
mylist = [-1,4,2,3,-10,2,4]

In [127]:
[x for x in mylist]

[-1, 4, 2, 3, -10, 2, 4]

In [128]:
[x**2 for x in mylist]

[1, 16, 4, 9, 100, 4, 16]

* Get the sublist of `mylist` containing only even numbers.

In [129]:
[x for x in mylist if x%2 == 0]

[4, 2, -10, 2, 4]

* Replace each negative number in `mylist` with zero.

Notice now the syntax difference!

In [131]:
mylist

[-1, 4, 2, 3, -10, 2, 4]

In [130]:
[x if x >= 0 else 0 for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

In [132]:
[0 if x < 0 else x for x in mylist]

[0, 4, 2, 3, 0, 2, 4]

* Make the length 8 list of lists `[[0,1,2],[0,1,2],...,[0,1,2]]`.

In [133]:
[[0,1,2] for _ in range(8)]

[[0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2]]

In [134]:
len([[0,1,2] for _ in range(8)])

8

* Make the length 24 list `[0,1,2,0,1,2,0,1,2...]`

Let's try this one with a for-loop first, and then see how we could do it with list comprehension.

In [137]:
mylist2 = []
for i in range(8):
    for j in range(3):
        mylist2.append(j)
mylist2

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

In [138]:
len(mylist2)

24

In [139]:
[j for i in range(8) for j in range(3)]

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]

* Capitalize each word in the catalogue description of Math 9:


Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.

In [141]:
s = '''Introduction to computers and programming using Matlab and Python. Representation of numbers and precision, input/output, functions, custom data types, testing/debugging, reading exceptions, plotting data, numerical differentiation, basics of algorithms. Analysis of random processes using computer simulations.'''

In [143]:
#Notice this goes character by character
#[c for c in s]

In [145]:
#This splits the string s at the spaces
wordlist = s.split()

In [148]:
caplist = [c.capitalize() for c in wordlist]

This is a list of capitalized words, the last thing to do is put it back together.

In [151]:
s2 = ' '.join(caplist)

In [152]:
s2

'Introduction To Computers And Programming Using Matlab And Python. Representation Of Numbers And Precision, Input/output, Functions, Custom Data Types, Testing/debugging, Reading Exceptions, Plotting Data, Numerical Differentiation, Basics Of Algorithms. Analysis Of Random Processes Using Computer Simulations.'

In [153]:
type(s2)

str

***

We'll get to this material starting on Friday.

## f-strings – Pythonic Code 2 

In [1]:
name = "Yasmeen"
n = 13

## lambda functions – Pythonic Code 3 

* Write a function `cap` that takes as input a string `s`, and as output returns the same string capitalized.

* Write a function `plus` that takes two inputs and adds them together.

* Make a $20 \times 3$ NumPy array of random letters, then concatenate each row of three letters into a single length-3 string using `np.apply_along_axis`.

* Let `tuplist` be the following list of tuples. Sort the list so that the numbers are increasing.

`[("A",50),("B",70),("C",100),("D",45)]`