## July 25th, 2024

## July 22nd, 2024

In [52]:
from datetime import datetime
datetime.strptime("2023-7-21", '%Y-%m-%d').strftime('%A')

'Friday'

Want to go from 15 to 21

In [56]:
[datetime.strptime(f"2023-7-{n}", '%Y-%m-%d').strftime('%A') for n in range(15,22)]

['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

In [23]:
f = lambda x: x**3-2
df = lambda x: 3*x**2
newt = lambda z: z - f(z)/df(z)

In [2]:
import numpy as np

In [24]:
z = np.linspace(-2,2,1000)
reps = 10
arr = np.zeros((len(z),reps+1))
arr[:,0] = z

for i in range(reps):
    arr[:,i+1] = newt(arr[:,i])

In [25]:
results = arr[:,-1]

In [26]:
f(results)

array([2.79785675e-04, 5.12936568e-04, 9.17494194e-04, 1.60209214e-03,
       2.73251302e-03, 4.55491099e-03, 7.42510913e-03, 1.18442621e-02,
       1.85008573e-02, 2.83188516e-02, 4.25119203e-02, 6.26445748e-02,
       9.07025112e-02, 1.29177145e-01, 1.81172945e-01, 2.50550967e-01,
       3.42128046e-01, 4.61958952e-01, 6.17739424e-01, 8.19383437e-01,
       1.07985140e+00, 1.41634265e+00, 1.85202387e+00, 2.41855896e+00,
       3.15985849e+00, 4.13771998e+00, 5.44045473e+00, 7.19632736e+00,
       9.59491632e+00, 1.29218130e+01, 1.76163511e+01, 2.43702069e+01,
       3.43007708e+01, 4.92660088e+01, 7.24573936e+01, 1.09563129e+02,
       1.71159070e+02, 2.77893621e+02, 4.72454489e+02, 8.49292064e+02,
       1.63523128e+03, 3.43287613e+03, 8.06134779e+03, 2.20125838e+04,
       7.44436637e+04, 3.49137449e+05, 2.87542667e+06, 7.93398700e+07,
       2.87223095e+11, 5.31610870e+09, 2.03755896e+07, 1.17061645e+06,
       1.67837131e+05, 3.83285215e+04, 1.16131809e+04, 4.25537232e+03,
      

In [28]:
good_bool = np.abs(f(results)) < 0.0001

In [46]:
f(arr[good_bool,-1])

array([8.47063470e-05, 2.31195515e-05, 5.63304823e-06, 1.21696353e-06,
       2.31512195e-07, 3.85077890e-08, 5.55960522e-09, 6.91561031e-10,
       7.35544958e-11, 6.63735733e-12, 5.04485342e-13, 3.19744231e-14,
       1.33226763e-15, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [43]:
np.abs(f(results)) < 0.0001

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [32]:
good_bool.sum()

754

In [8]:
good_bool.shape

(1000,)

In [9]:
f(good_bool)

array([-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
       -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
       -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
       -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
       -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
       -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
       -2, -2, -2, -2, -2, -2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -2, -2, -2,
       -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
       -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
       -2, -2, -2, -2, -2

## July 18th, 2024

In [1]:
import numpy as np
rng = np.random.default_rng()

In [28]:
arr = rng.choice([-1,1],size=(10,10),p=[0.9,0.1])
arr

array([[ 1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1,  1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1,  1, -1, -1, -1],
       [-1,  1,  1, -1, -1, -1,  1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [45]:
(arr == 1).sum()

11

In [35]:
np.count_nonzero(arr == 1)/100

0.11

In [31]:
x = rng.choice([-1,1],size=20)
x

array([ 1,  1,  1, -1, -1,  1,  1, -1, -1, -1,  1, -1,  1,  1,  1,  1, -1,
       -1,  1, -1])

In [29]:
(arr == -1).sum()

89

In [2]:
help(rng.choice)

Help on built-in function choice:

choice(...) method of numpy.random._generator.Generator instance
    choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)
    
    Generates a random sample from a given array
    
    Parameters
    ----------
    a : {array_like, int}
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated from np.arange(a).
    size : {int, tuple[int]}, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn from the 1-d `a`. If `a` has more
        than one dimension, the `size` shape will be inserted into the
        `axis` dimension, so the output ``ndim`` will be ``a.ndim - 1 +
        len(size)``. Default is None, in which case a single value is
        returned.
    replace : bool, optional
        Whether the sample is with or without replacement. Default is True,
        meaning that a value of ``a`` can be selected m

In [8]:
range(4)

range(0, 4)

In [9]:
list(range(4))

[0, 1, 2, 3]

In [10]:
for i in range(4):
    print(i)

0
1
2
3


In [11]:
for i in [0,1,2,3]:
    print(i)

0
1
2
3


In [12]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash

In [13]:
arr = np.zeros((4,4),dtype=int)

In [14]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
arr[0]

array([0, 0, 0, 0])

In [17]:
arr[0] = 1
arr

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
for i in range(4):
    arr[i] = i
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [20]:
list(range(4))

[0, 1, 2, 3]